name: messenger_clone
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  google_sign_in: ^5.2.3
  shared_preferences: ^2.0.13
  random_string: ^2.3.1
  cloud_firestore: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
